/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

/**
 *
 * @author RuslanLopez
 */
public class QuizAdmin extends javax.swing.JFrame {

    /**
     * Creates new form QuizAdmin
     */
    public QuizAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionButtonsGroup = new javax.swing.ButtonGroup();
        pnlDatosPregunta = new javax.swing.JPanel();
        lblEnunciado = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        lblTipoPregunta = new javax.swing.JLabel();
        cmbTipoPregunta = new javax.swing.JComboBox<>();
        lblOpciones = new javax.swing.JLabel();
        lblOpciones.setVisible(false);
        pnlOpciones = new javax.swing.JPanel();
        pnlOpciones.setVisible(false);
        agregarOpcion = new javax.swing.JButton();
        quitarOpcion = new javax.swing.JButton();
        pnlOpcionesRespuesta = new javax.swing.JScrollPane();
        lblRespuesta = new javax.swing.JLabel();
        pnlRespuesta = new javax.swing.JPanel();
        scrollBlancos = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        pnlControles = new javax.swing.JPanel();
        pnlQuestionCreationDeletion = new javax.swing.JPanel();
        btnQuitarPregunta = new javax.swing.JButton();
        btnAgregarPregunta = new javax.swing.JButton();
        pnlQuestionNavigation = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguente = new javax.swing.JButton();
        btnIrAUnaEspecífica = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatosPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de pregunta"));
        pnlDatosPregunta.setLayout(new java.awt.GridLayout(0, 2));

        lblEnunciado.setText("Enunciado");
        pnlDatosPregunta.add(lblEnunciado);

        txtEnunciado.setEditable(false);
        pnlDatosPregunta.add(txtEnunciado);

        lblTipoPregunta.setText("tipo de pregunta:");
        pnlDatosPregunta.add(lblTipoPregunta);

        cmbTipoPregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llenar el espacio en blanco", "Opción Múltiple", "Respuesta Múltiple" }));
        pnlDatosPregunta.add(cmbTipoPregunta);

        lblOpciones.setText("opciones");
        pnlDatosPregunta.add(lblOpciones);

        agregarOpcion.setText("+");
        agregarOpcion.setEnabled(false);

        quitarOpcion.setText("-");
        quitarOpcion.setEnabled(false);

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcionesRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitarOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpcionesRespuesta)
                    .addGroup(pnlOpcionesLayout.createSequentialGroup()
                        .addComponent(agregarOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitarOpcion)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlDatosPregunta.add(pnlOpciones);

        lblRespuesta.setText("respuesta");
        pnlDatosPregunta.add(lblRespuesta);

        pnlRespuesta.setMinimumSize(new java.awt.Dimension(100, 90));
        pnlRespuesta.setPreferredSize(new java.awt.Dimension(200, 90));
        pnlRespuesta.setLayout(new java.awt.BorderLayout());

        txtRespuesta.setEditable(false);
        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        txtRespuesta.setEnabled(false);
        scrollBlancos.setViewportView(txtRespuesta);

        pnlRespuesta.add(scrollBlancos, java.awt.BorderLayout.CENTER);

        pnlDatosPregunta.add(pnlRespuesta);

        getContentPane().add(pnlDatosPregunta, java.awt.BorderLayout.CENTER);

        pnlControles.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        pnlControles.setLayout(new java.awt.BorderLayout());

        pnlQuestionCreationDeletion.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlQuestionCreationDeletion.setLayout(new java.awt.BorderLayout());

        btnQuitarPregunta.setText("-");
        btnQuitarPregunta.setEnabled(false);
        pnlQuestionCreationDeletion.add(btnQuitarPregunta, java.awt.BorderLayout.EAST);

        btnAgregarPregunta.setText("+");
        btnAgregarPregunta.setEnabled(false);
        pnlQuestionCreationDeletion.add(btnAgregarPregunta, java.awt.BorderLayout.WEST);

        pnlControles.add(pnlQuestionCreationDeletion, java.awt.BorderLayout.NORTH);

        pnlQuestionNavigation.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlQuestionNavigation.setLayout(new java.awt.BorderLayout());

        btnAnterior.setText("<");
        btnAnterior.setEnabled(false);
        pnlQuestionNavigation.add(btnAnterior, java.awt.BorderLayout.WEST);

        btnSiguente.setText(">");
        btnSiguente.setEnabled(false);
        pnlQuestionNavigation.add(btnSiguente, java.awt.BorderLayout.EAST);

        btnIrAUnaEspecífica.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        btnIrAUnaEspecífica.setEnabled(false);
        pnlQuestionNavigation.add(btnIrAUnaEspecífica, java.awt.BorderLayout.CENTER);

        pnlControles.add(pnlQuestionNavigation, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlControles, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarOpcion;
    private javax.swing.JButton btnAgregarPregunta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JComboBox<String> btnIrAUnaEspecífica;
    private javax.swing.JButton btnQuitarPregunta;
    private javax.swing.JButton btnSiguente;
    private javax.swing.JComboBox<String> cmbTipoPregunta;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblTipoPregunta;
    private javax.swing.ButtonGroup optionButtonsGroup;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JPanel pnlDatosPregunta;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JScrollPane pnlOpcionesRespuesta;
    private javax.swing.JPanel pnlQuestionCreationDeletion;
    private javax.swing.JPanel pnlQuestionNavigation;
    private javax.swing.JPanel pnlRespuesta;
    private javax.swing.JButton quitarOpcion;
    private javax.swing.JScrollPane scrollBlancos;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
